openapi: 3.0.3

info:
  title: Application API
  description: |
    This API allows client to fetch all information regarding current application state, like API and client
    minimal supported versions.
  version: 0.2.0
  x-release-notes:
    - 0.2.0 Expose availability endpoints.
    - 0.1.3 Refactor ErrorResponse file location.
    - 0.1.2 Add required definition in VersionList schema and change Player API name.
    - 0.1.1 Expand version value to support patch versions.
    - 0.1.0 Expose get versions endpoint.

tags:
  - name: Application
    description: All actions related to the application state.

paths:
  /versions:
    get:
      summary: API and client version list.
      description: Retrieve versions of each used client and API.
      operationId: getVersionList
      tags:
        - Application
      parameters:
        # headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
      responses:
        '200':
          $ref: '#/components/responses/GetVersionListResponse'
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /availability:
    get:
      summary: Available features for current client.
      description: |
        Retrieve information about the application or its features that are available to the current client application.
        If client request for a feature that is not available, request will result with an error, most commonly HTTP status 451.
      operationId: getAvailability
      tags:
        - Application
      parameters:
        # headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
      responses:
        '200':
          $ref: '#/components/responses/GetFeatureListResponse'
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

components:
  responses:
    GetVersionListResponse:
      description: Get version list response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VersionList'

    GetFeatureListResponse:
      description: Get feature list response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatureList'

  schemas:
    VersionList:
      type: object
      description: |
        Object that holds list of versions for each component. Pagination is not supported as number of items is predefined and small.
      required:
        - clients
        - apis
      properties:
        clients:
          type: array
          description: List of clients and their current and minimum supported versions.
          items:
            $ref: '#/components/schemas/ClientVersion'
        apis:
          type: array
          description: List of API-s and their current and minimum supported versions.
          items:
            $ref: '#/components/schemas/ServerVersion'

    ClientVersion:
      type: object
      description: Object that holds information of current and minimum supported version of the client.
      allOf:
        - $ref: '#/components/schemas/Version'
        - type: object
          properties:
            type:
              $ref: '#/components/schemas/ClientType'

    ClientType:
      type: string
      description: Type of the client.
      example: 'ANDROID_CLIENT'
      enum:
        - ANDROID_CLIENT
        - IOS_CLIENT

    ServerVersion:
      type: object
      description: Object that holds information of current and minimum supported API version.
      allOf:
        - $ref: '#/components/schemas/Version'
        - type: object
          properties:
            type:
              $ref: '#/components/schemas/ServerApiType'

    ServerApiType:
      type: string
      description: API group.
      example: 'MIX_API'
      enum:
        - APPLICATION_API
        - AUTH_API
        - COMMUNITY_API
        - EXPLORE_API
        - MIX_API
        - PLAYER_API
        - USER_API

    Version:
      type: object
      description: Object that holds information of current and minimum supported version of the resource.
      required:
        - minVersion
        - currentVersion
      properties:
        minVersion:
          $ref: '#/components/schemas/VersionValue'
        currentVersion:
          $ref: '#/components/schemas/VersionValue'
        deprecationDate:
          type: string
          description: Date when resource will be deprecated. Client should consult documentation for upgrade details.
          format: date
          example: '9999-01-01'
        notice:
          type: string
          description: Human readable notice for deprecation of the resource.
          example: 'Application API has required breaking change in version 2, and version 1 is not used by major clients.'

    VersionValue:
      type: string
      description: Version of the item.
      pattern: '^\d+\.\d+.\d+$'
      example: '1.2.1'

    FeatureList:
      type: object
      description: |
        Object that hold list of features that are available or unavailable to the client. There is no pagination as feature list has small amount of items.
      required:
        - features
      properties:
        features:
          type: array
          description: List of features that are available or unavailable to the client.
          items:
            $ref: '#/components/schemas/Feature'
          example:
            - type: APPLICATION
              available: false

    Feature:
      type: object
      description: Specific feature.
      required:
        - type
        - available
      properties:
        type:
          $ref: '#/components/schemas/FeatureType'
        available:
          type: boolean
          description: If value is true, then this feature is available to the client.
          example: true

    FeatureType:
      type: string
      description: |
        List of features is defined in this enum. Possible features are:
          * APPLICATION - define application availability for this client. If false, client can't use this application - e.g. user traveled to unsupported country.
      enum:
        - APPLICATION
      example: APPLICATION