openapi: 3.0.3

info:
  title: Player API
  description: |
    This API allows client to start or fetch current user play session, as well as interaction with current mix and track,
    such as play, pause, skip, increase volume, like etc.
    
    Note: Main subject in Player API is track in context of specific mix, so all endpoints are actions against that track.
  version: 0.2.0
  x-release-notes:
    - 0.2.0 Add reactions endpoints and refactor common data model
    - 0.1.0 Exposed endpoints for play, pause, skip, change-volume, like, dislike, recommend, do-not-recommend and report. Also endpoints for fetching track list and play session.

tags:
  - name: Player
    description: Available interactions from the player screen.
  - name: Session
    description: Available actions for session fetch and management.
  - name: Track
    description: Available interactions on track list or specific track.

paths:
  /player-session:
    get:
      summary: Fetch currently active player session.
      description: |
        For current user return info about active player session, like: last played or currently playing track and mix.
        This info can be used when user relaunch the client application, so she/he can continue playing last played track/mix.
        Also, this can be used when user is active on multiple platforms to synchronize "now playing" information.
        If user does not have active session, error 404 will be returned.
      operationId: getPlayerSession
      tags:
        - Session
      parameters:
        #headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
      responses:
        '200':
          $ref: '#/components/responses/GetSessionResponse'
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /player/{mixId}/play:
    post:
      summary: Fetch current track and start playing.
      description: Client can fetch current track from specific mix and start playing it.
      operationId: playTrack
      tags:
        - Player
      parameters:
        #headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        - $ref: './components/headers.yaml#/components/parameters/X-Idempotency-Key'
        # path parameter
        - $ref: './components/parameters.yaml#/components/parameters/MixIdentifier'
      responses:
        '200':
          $ref: '#/components/responses/GetTrackResponse'
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /player/{mixId}/pause:
    post:
      summary: Pause currently played track.
      description: Client can pause currently played track. This info is used for better recommendations.
      operationId: pauseTrack
      tags:
        - Player
      parameters:
        #headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        - $ref: './components/headers.yaml#/components/parameters/X-Idempotency-Key'
        # path parameter
        - $ref: './components/parameters.yaml#/components/parameters/MixIdentifier'
      responses:
        '204':
          description: User successfully paused the track.
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /player/{mixId}/next:
    post:
      summary: Fetch next track after current one is finished.
      description: |
        After current track is finished (or almost finished) client can fetch next one. If there is no next tracks, error 404 will be thrown.
      operationId: nextTrack
      tags:
        - Player
      parameters:
        #headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        - $ref: './components/headers.yaml#/components/parameters/X-Idempotency-Key'
        # path parameter
        - $ref: './components/parameters.yaml#/components/parameters/MixIdentifier'
      responses:
        '200':
          $ref: '#/components/responses/GetTrackResponse'
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /player/{mixId}/skip:
    post:
      summary: Skip current track and fetch next one.
      description: |
        Client can skip current track from specific mix and play next one. If there is no next tracks, error 404 will be thrown.
      operationId: skipTrack
      tags:
        - Player
      parameters:
        #headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        - $ref: './components/headers.yaml#/components/parameters/X-Idempotency-Key'
        # path parameter
        - $ref: './components/parameters.yaml#/components/parameters/MixIdentifier'
      responses:
        '200':
          $ref: '#/components/responses/GetTrackResponse'
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /player/{mixId}/change-volume:
    post:
      summary: Change volume of current track.
      description: Client can change volume of currently playing track. This info is used for better recommendations.
      operationId: changeTrackVolume
      tags:
        - Player
      parameters:
        #headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        - $ref: './components/headers.yaml#/components/parameters/X-Idempotency-Key'
        # path parameter
        - $ref: './components/parameters.yaml#/components/parameters/MixIdentifier'
      requestBody:
        $ref: '#/components/requestBodies/ChangeVolumeRequest'
      responses:
        '204':
          description: User successfully changed the volume of the track.
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /tracks/{mixId}:
    get:
      summary: Get track list for specific mix.
      description: |
        Return only played tracks from specific mix for currently active user.
        If user listened the whole mix or did not listen to any song from the mix, empty collection will be returned.
      operationId: getTrackList
      tags:
        - Track
      parameters:
        # headers
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        # path parameter
        - $ref: './components/parameters.yaml#/components/parameters/MixIdentifier'
      responses:
        '200':
          $ref: '#/components/responses/GetTrackListResponse'
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

  /tracks/{trackId}/reactions:
    post:
      summary: React to specific track.
      description: Current active user can react to specific track, e.g. like it, dislike it or put it on recommend list.
      operationId: react
      tags:
        - Track
      parameters:
        # headers
        - $ref: './components/headers.yaml#/components/parameters/Authorization'
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        - $ref: './components/headers.yaml#/components/parameters/X-Idempotency-Key'
        # path parameter
        - $ref: '#/components/parameters/TrackIdentifier'
      requestBody:
        $ref: './components/parameters.yaml#/components/requestBodies/CreateReactionRequest'
      responses:
        '204':
          description: User successfully reacted to the track.
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

    delete:
      summary: Remove reaction to the specific track.
      description: Current active user can remove reaction to the specific track.
      operationId: removeReaction
      tags:
        - Track
      parameters:
        # headers
        - $ref: './components/headers.yaml#/components/parameters/Authorization'
        - $ref: './components/headers.yaml#/components/parameters/X-Accept-Version'
        - $ref: './components/headers.yaml#/components/parameters/X-Idempotency-Key'
        # path parameter
        - $ref: '#/components/parameters/TrackIdentifier'
      requestBody:
        $ref: './components/parameters.yaml#/components/requestBodies/CreateReactionRequest'
      responses:
        '204':
          description: User successfully removed reaction.
        default:
          $ref: './components/responses.yaml#/components/responses/ErrorResponse'

components:
  parameters:
    TrackIdentifier:
      name: trackId
      in: path
      required: true
      schema:
        $ref: './components/common.yaml#/components/schemas/Identifier'

  requestBodies:
    ChangeVolumeRequest:
      description: Change volume request.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VolumeValue'

  responses:
    GetSessionResponse:
      description: Get active user play session.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Session'

    GetTrackResponse:
      description: Get track.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Track'

    GetTrackListResponse:
      description: Get list of tracks.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrackList'

  schemas:
    Session:
      type: object
      description: Information about current active user session.
      required:
        - mixId
        - track
      properties:
        mixId:
          type: string
          description: The unique mix identifier used for fetching specific set of information.
          example: 'V1StGXR8z5'
        track:
          $ref: '#/components/schemas/Track'
        device:
          $ref: '#/components/schemas/SessionDevice'

    SessionDevice:
      type: object
      description: Device where session is active.
      required:
        - name
        - type
      properties:
        name:
          type: string
          description: User defined device name.
          example: 'Samsung TV - Living Room'
        type:
          type: string
          description: Device type.
          enum:
            - CONSOLE
            - PHONE
            - TV
            - WATCH
            - WEB

    TrackList:
      type: object
      description: List of listened tracks in current mix. There is no pagination as track list has small amount of items.
      required:
        - tracks
      properties:
        tracks:
          type: array
          items:
            $ref: '#/components/schemas/Track'

    Track:
      type: object
      description: All related information about the track.
      required:
        - identifier
        - name
        - artists
        - album
        - streamUrl
        - duration
      properties:
        identifier:
          $ref: './components/common.yaml#/components/schemas/Identifier'
        name:
          type: string
          description: Human friendly track name.
          example: 'The Great Gig in the Sky'
        artists:
          type: array
          description: List of track artist.
          default: [ ]
          items:
            $ref: './components/responses.yaml#/components/schemas/Creator'
          example:
            - username: 'V1StGXR8z5'
              displayName: 'Pink Floyd'
              avatarUrl: 'logo.png'
              active: true
        album:
          $ref: '#/components/schemas/Album'
        reactions:
          $ref: './components/responses.yaml#/components/schemas/UserReactions'
        streamUrl:
          type: string
          description: URL of the track available to play on the client. Note that this URL is dynamic for each request.
          example: 'song.mp3'
        duration:
          type: string
          format: ISO 8601 duration
          description: Duration of the track.
          example: 'PT1H25M14S'

    Album:
      type: object
      description: Album information.
      required:
        - identifier
        - displayName
        - releaseDate
      properties:
        identifier:
          $ref: './components/common.yaml#/components/schemas/Identifier'
        displayName:
          type: string
          description: Human friendly album name.
          example: 'The Dark Side of the Moon'
        releaseDate:
          type: string
          description: Album release date.
          format: date
          example: '1973-03-01'

    VolumeValue:
      type: object
      description: New volume value.
      required:
        - value
      properties:
        value:
          type: integer
          description: Volume value.
          minimum: 0
          maximum: 100
          example: 57