openapi: 3.0.3
info:
  title: Test endpoint
  description: Test endpoint
  version: 1.0.0

tags:
  - name: test

paths:
  /test:
    get:
      tags:
        - test
      responses:
        '200':
          $ref: '#/components/responses/GetTestResponse'
        default:
          $ref: './components/errors.yaml#/components/responses/ErrorResponse'

components:
  responses:
    GetTestResponse:
      description: Test data response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TestData'

  schemas:
    TestData:
      properties:
        test:
          type: string
