server:
  port: 80

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/musicmixerai
  jpa:
    show-sql: true

  application.name: mixer-gateway
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  liquibase:
    change-log: database/changelogs.xml
    enabled: true
  jpa.open-in-view: false
  thymeleaf.check-template-location: false
  jackson.default-property-inclusion: non_null
  datasource:
    url: ${SERVICE_DATABASE_URL:jdbc:postgresql://localhost:15430/mixer-gateway}
    username: ${SERVICE_DATABASE_USERNAME:mixer-gateway}
    password: ${SERVICE_DATABASE_PASSWORD:mixer-gateway}

logging:
  level:
    root: info
    org.zalando.logbook: trace

logbook:
  predicate:
    exclude:
      - path: favicon.ico
        methods:
          - GET
      - path: /actuator/**
        methods:
          - GET

mixer-gateway:
  security:
    enabled: true
    http-basic:
      enabled: ${SERVICE_HTTP_BASIC_AUTH_ENABLE:false}
      clients:
        - username: ${SERVICE_ADAPTY_CLIENT_USERNAME}
          password: ${SERVICE_ADAPTY_CLIENT_PASSWORD}
          roles:
            - PAYMENT_CLIENT
  circuitbreaker:
    timelimiter.timeout-duration: 1m
    ignore-exceptions:
      - feign.FeignException.FeignClientException
  integration:
    feign:
      TestApi.url: ${USER_SERVICE_URL:http://localhost:8001}
  cors:
    allowed-origins:
      - "https://**.mixer.fm"
      - "https://mixer.fm"
  openapi:
    validation:
      specifications:
        - name: application-v1
          paths:
            - /versions
            - /availability
        # TODO uncomment
        #- name: community-v1
        #  paths:
        #    - /comments/*
        - name: player-v1
          paths:
            - /player/*/play
            - /player/*/pause
            - /player/*/next
            - /player/*/skip
            - /player/*/change-volume
            - /player-session
            - /tracks/*
            - /tracks/*/reactions
        - name: mix-v1
          paths:
            - /mixes/*
            - /mixes/*/reactions
            - /mixes/*/uploaded
            - /mixes/*/liked
            - /mixes/*/listened
            - /collections
            - /collections/*
            - /collections/*
        - name: user-v1
          paths:
            - /users
            - /users/*
            - /users/*/followers
            - /users/*/following
            - /users/*/follow
            - /users/*/unfollow
            - /users/*/remove-follower
            - /users/*/reactions
            - /current-user
            - /newsletters/subscription
  availability:
    excluded-endpoints:
      - /versions
      - /availability
      - /actuator/*
    supported-countries:
      - HR
  versions:
    clients:
      ANDROID_CLIENT:
        min-version: 1.0.0
        current-version: 1.0.0
      IOS_CLIENT:
        min-version: 1.0.0
        current-version: 1.0.0
    apis:
      APPLICATION_API:
        min-version: 1.0.0
        current-version: 1.0.0
      AUTH_API:
        min-version: 1.0.0
        current-version: 1.0.0
      COMMUNITY_API:
        min-version: 1.0.0
        current-version: 1.0.0
      EXPLORE_API:
        min-version: 1.0.0
        current-version: 1.0.0
      MIX_API:
        min-version: 1.0.0
        current-version: 1.0.0
      PLAYER_API:
        min-version: 1.0.0
        current-version: 1.0.0
      USER_API:
        min-version: 1.0.0
        current-version: 1.0.0
  mix-types:
    GEM:
      number-of-likes: 5
      play-count: 10
    GOLD:
      number-of-likes: 100
    PLATINUM:
      number-of-likes: 1000
    DIAMOND:
      number-of-likes: 10000
  user-colors:
    active:
      - "#5456D0"
      - "#78E1AC"
      - "#F781CF"
      - "#B084CC"
      - "#379392"
      - "#F7624D"
      - "#33A1FD"
      - "#F4BD0F"
      - "#EF959C"
    inactive: "#5A5A5A"