server:
  port: 80

spring:
  jpa:
    show-sql: true

  application.name: mixer-gateway
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  liquibase:
    change-log: database/changelogs.xml
    enabled: true
  jpa.open-in-view: false
  thymeleaf.check-template-location: false
  jackson.default-property-inclusion: non_null
  datasource:
    url: ${SERVICE_DATABASE_URL:jdbc:postgresql://localhost:15430/mixer-gateway}
    username: ${SERVICE_DATABASE_USERNAME:mixer-gateway}
    password: ${SERVICE_DATABASE_PASSWORD:mixer-gateway}

mixer-gateway:
  circuitbreaker:
    timelimiter.timeout-duration: 1m
    ignore-exceptions:
      - feign.FeignException.FeignClientException
  integration:
    feign:
      TestApi.url: ${USER_SERVICE_URL:http://localhost:8001}
  openapi:
    validation:
      specifications:
        - name: mix-v1
          paths:
            - /mixes/**
  versions:
    clients:
      ANDROID_CLIENT:
        minVersion: 1.0
        currentVersion: 1.0
      IOS_CLIENT:
        minVersion: 1.0
        currentVersion: 1.0
    apis:
      APPLICATION_API:
        minVersion: 1.0
        currentVersion: 1.0
      AUTH_API:
        minVersion: 1.0
        currentVersion: 1.0
      COMMUNITY_API:
        minVersion: 1.0
        currentVersion: 1.0
      EXPLORE_API:
        minVersion: 1.0
        currentVersion: 1.0
      MIX_API:
        minVersion: 1.0
        currentVersion: 1.0
      PLAY_API:
        minVersion: 1.0
        currentVersion: 1.0
      USER_API:
        minVersion: 1.0
        currentVersion: 1.0

